const fs = require('fs'), R = p => JSON.parse(fs.readFileSync('content/' + p + '.json', 'utf8'));
const c = R('company'), h = R('home'), ct = R('contact'), pf = R('portfolio');
const e = s => String(s ?? '').replace(/[&<>"]/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]));
const tbd = (v, l) => v ? e(v) : `<mark>[${l} – nog aan te vullen]</mark>`;
const page = (file, title, desc, body) => `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${e(title)}</title><meta name="description" content="${e(desc)}"><link rel="canonical" href="${e(c.domain)}/${file === 'index.html' ? '' : file}">
<meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(desc)}"><meta property="og:type" content="website"><meta property="og:image" content="${e(c.domain)}/images/logo.png">
<link rel="icon" href="/images/logo.png"><script>document.documentElement.className="js"</script><link rel="stylesheet" href="/css/style.css"><style>:root{--primary:${e(c.colorPrimary)};--accent:${e(c.colorAccent)}}</style>
<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: c.name, url: c.domain, email: c.email, telephone: c.phone, address: c.address, areaServed: "BE" })}</script></head>
<body><a class="skip" href="#main">Naar de inhoud</a>
<header><div class="wrap"><a class="brand" href="/"><img src="/images/logo.png" alt="" width="40" height="40"></a><nav aria-label="Hoofdmenu"><a href="/">Home</a><a href="/contact.html">Contact</a></nav></div></header>
<main id="main">${body}</main>
<footer><div class="wrap"><nav aria-label="Juridisch"><a href="/wettelijke-vermeldingen.html">Wettelijke vermeldingen</a><a href="/privacy.html">Privacyverklaring</a><a href="/cookies.html">Cookiebeleid</a><a href="/algemene-voorwaarden.html">Algemene voorwaarden</a><a href="#" class="cookie-settings">Cookie-instellingen</a></nav>
<p>© ${new Date().getFullYear()} ${e(c.name)}</p><p class="pw">Powered by <span title="Gust's Web Designs">GWD</span></p></div></footer>
<div id="cb" role="dialog" aria-label="Cookies" hidden><p>Deze website gebruikt enkel functionele opslag om je keuze te onthouden. Er zijn geen analytische of marketingcookies. <a href="/cookies.html">Meer info</a></p><button class="btn" id="cb-yes">Accepteren</button><button class="btn" id="cb-no">Weigeren</button></div>
<script src="/js/main.js"></script></body></html>`;
const legal = (t, secs) => `<section><div class="wrap"><h1>${t}</h1>${secs.map(([a, b]) => `<h2>${a}</h2>${b}`).join('')}</div></section>`;
const out = {}; const W = (f, s) => { fs.writeFileSync('dist/' + f, s); out[f] = 1 };
fs.rmSync('dist', { recursive: true, force: true }); fs.cpSync('static', 'dist', { recursive: true });
fs.cpSync('content', 'dist/content', { recursive: true });
W('index.html', page('index.html', h.title, h.description, `<div class="hero"><span class="blob b1" aria-hidden="true"></span><span class="blob b2" aria-hidden="true"></span><span class="blob b3" aria-hidden="true"></span><div class="wrap"><h1>${e(h.heroTitle)}</h1><p>${e(h.heroText)}</p><a class="btn" href="/contact.html">${e(h.cta)}</a></div></div>
<section><div class="wrap"><h2 class="reveal">${e(h.servicesTitle)}</h2><div class="grid">${h.services.map(s => `<div class="card reveal"><h3>${e(s.title)}</h3><p>${e(s.text)}</p></div>`).join('')}</div></div></section>
<section><div class="wrap"><h2 class="reveal">${e(h.portfolioTitle)}</h2><p class="reveal">${e(h.portfolioIntro)}</p><div class="grid">${pf.items.map(i => `<a class="card reveal" href="${e(i.url)}" rel="noopener" target="_blank"><img src="${e(i.image)}" alt="Website ${e(i.name)}" loading="lazy" width="640" height="400"><p>${e(i.name)}</p></a>`).join('')}</div></div></section>`));
W('contact.html', page('contact.html', ct.title, ct.description, `<section><div class="wrap"><h1>${e(ct.heading)}</h1><p>${e(ct.intro)}</p><p>${e(c.email)} · ${e(c.phone)}<br>${e(c.hours)}</p>
<form id="cf" data-to="${e(c.email)}"><label for="name">Naam</label><input id="name" name="name" required autocomplete="name"><label for="email">E-mail</label><input id="email" name="email" type="email" required autocomplete="email"><label for="message">Bericht</label><textarea id="message" name="message" rows="5" required></textarea>
<div class="hp" aria-hidden="true"><label>Niet invullen<input name="website" tabindex="-1" autocomplete="off"></label></div>
<label style="font-weight:400"><input type="checkbox" required style="width:auto"> Ik heb de <a href="/privacy.html">privacyverklaring</a> gelezen.</label><p><button class="btn" type="submit">Verstuur</button></p></form></div></section>`));
W('wettelijke-vermeldingen.html', page('x', 'Wettelijke vermeldingen – ' + c.name, 'Wettelijke vermeldingen', legal('Wettelijke vermeldingen', [['Uitgever', `<p>${e(c.name)}, ${e(c.legalForm)}<br>Zetel: ${e(c.address)}<br>E-mail: ${e(c.email)} · Tel: ${e(c.phone)}<br>Ondernemingsnummer (KBO): ${tbd(c.kbo, 'KBO')}<br>BTW-nummer: ${tbd(c.vat, 'BTW')}</p>`], ['Toezicht',`<p>Geen gereglementeerd beroep; geen beroepsorganisatie of toezichthouder van toepassing. Ondernemingsrechtbank: Nederlandstalige Ondernemingsrechtbank Brussel.</p>`], ['Prijzen', '<p>Prijzen worden per offerte meegedeeld en vermelden of BTW is inbegrepen.</p>'], ['Disclaimer en intellectuele eigendom', '<p>Alle teksten, beelden en ontwerpen zijn beschermd door auteursrecht en mogen niet zonder toestemming worden gebruikt. Wij streven naar correcte informatie maar aanvaarden geen aansprakelijkheid voor onvolledigheden of externe links. Portfolio-afbeeldingen worden getoond met toestemming van de betrokken klanten.</p>']])));
W('privacy.html', page('x', 'Privacyverklaring – ' + c.name, 'Privacyverklaring', legal('Privacyverklaring', [['Verwerkingsverantwoordelijke', `<p>${e(c.name)}, ${e(c.address)}. Contact: ${e(c.privacyContact)}.</p>`], ['Welke gegevens en waarom', '<p>Via het contactformulier: naam, e-mailadres en bericht, om je vraag te beantwoorden (rechtsgrond: toestemming / precontractuele maatregelen). Bewaartermijn: maximaal 24 maanden na het laatste contact.</p>'], ['Ontvangers', '<p>Het formulier opent je eigen e-mailprogramma; berichten komen terecht in onze mailbox (Gmail/Google). Hosting: Cloudflare Pages. Er worden geen analytics of externe lettertypes geladen.</p>'], ['Je rechten', '<p>Inzage, verbetering, verwijdering, beperking, bezwaar en overdraagbaarheid: mail naar ' + e(c.email) + '. Klacht: Gegevensbeschermingsautoriteit, Drukpersstraat 35, 1000 Brussel, www.gegevensbeschermingsautoriteit.be.</p>']])));
W('cookies.html', page('x', 'Cookiebeleid – ' + c.name, 'Cookiebeleid', legal('Cookiebeleid', [['Gebruikte opslag', '<p>Enkel functionele opslag (localStorage, sleutel “gwd-consent”) om je cookiekeuze te onthouden. Geen analytische of marketingcookies; er worden geen externe scripts geladen.</p>'], ['Keuze wijzigen', '<p>Klik op “Cookie-instellingen” in de footer om je keuze op elk moment te wijzigen of in te trekken.</p>']])));
W('algemene-voorwaarden.html', page('x', 'Algemene voorwaarden – ' + c.name, 'Algemene voorwaarden', legal('Algemene voorwaarden', [['Toepassing', `<p>Deze voorwaarden gelden voor alle offertes en overeenkomsten van ${e(c.name)} voor het ontwerpen, verkopen en onderhouden van websites.</p>`], ['Offertes en betaling', '<p>Offertes zijn 30 dagen geldig. Betalingstermijn en voorschot staan in de offerte. Prijzen vermelden of BTW inbegrepen is.</p>'], ['Levering en eigendom', '<p>Na volledige betaling verkrijgt de klant het gebruiksrecht op de website. Elke opgeleverde site vermeldt “Powered by GWD” in de footer.</p>'], ['Onderhoud', '<p>Onderhoud gebeurt volgens de afgesproken formule; naast bewijsbare gebreken geldt geen resultaatsverbintenis voor zoekmachinepositie.</p>'], ['Aansprakelijkheid en klachten',`<p>Klachten kunnen binnen 14 dagen na levering gemeld worden via ${e(c.email)}. Op deze voorwaarden is Belgisch recht van toepassing. Geschillen behoren tot de bevoegdheid van de Nederlandstalige Ondernemingsrechtbank Brussel.</p>`]])));
const site = { company: c, home: h, contact: ct, portfolio: pf }; fs.writeFileSync('dist/site-data.json', JSON.stringify(site, null, 2));
fs.writeFileSync('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', 'contact.html', 'wettelijke-vermeldingen.html', 'privacy.html', 'cookies.html', 'algemene-voorwaarden.html'].map(p => `<url><loc>${c.domain}/${p}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt', `User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ${c.domain}/sitemap.xml\n`);
console.log('OK');
